# Site settings
title: Golden Viking
email: info@goldenviking.org
description: "Golden Viking LLC is an experimental mobile software development operation.  We let our wild ideas fly."
baseurl: ""
url: "http://ogviking.github.io"

# Build settings
markdown: kramdown
permalink: pretty
